version: '2'
services:
    avahi:
        image: 'enernoclabs/avahi:v1'
        network_mode: 'host'
        restart: 'always'
        logging:
            driver: 'none'
    mongo:
        image: 'mongo'
        logging:
            driver: 'none'
    server:
        build: '.'
        command: 'gulp serve'
        ports:
            - '80:9000'
        volumes:
            - '/src/client/bower_components'
            - '/src/node_modules'
            - './:/src'
        links:
            - 'mongo'
